# config/packages/doctrine.yaml

doctrine:
    dbal:
        # DBAL leerá la conexión de esta variable de entorno
        driver: 'pdo_mysql'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        server_version: 'mariadb-10.4.17' # Puedes usar 'mariadb-10.4.17' o dejarlo como 'default'