monolog:
    channels: ['finpay_settlement', 'mute_automation'] # 1. Definimos el canal personalizado

    handlers:
        # ... otros handlers existentes (main, console, etc.) ...

        # 2. Configuración del Handler Específico
        finpay_settlement:
            type: stream
            # Ruta donde se guardará el archivo
            path: "%kernel.logs_dir%/transferencias_diarias.log"
            level: info
            channels: ["finpay_settlement"]
            # Formato simple para fácil lectura
            formatter: monolog.formatter.line

        mute_automation:
            type: stream
            path: "%kernel.logs_dir%/automatizacion_mute.log"
            level: info
            channels: ["mute_automation"]
            formatter: monolog.formatter.line