imports:
    - { resource: 'services_*.yaml' } 
    - { resource: '{%env(resolve:APP_ENV)%}/*.yaml', ignore_errors: true }

parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 


    App\:
        resource: '../src/'

    App\EventSubscriber\JwtTokenSubscriber:
        arguments:
            $jwtSecret: '%env(JWT_SECRET)%'
            
    App\Service\Notifier:
        arguments:
            $MAIL_HOST: '%env(MAIL_HOST)%'
            $MAIL_USERNAME: '%env(MAIL_USERNAME)%'
            $MAIL_PASSWORD: '%env(MAIL_PASSWORD)%'
            $MAIL_PORT: '%env(int:MAIL_PORT)%'         
            $MAIL_ENCRYPTION: '%env(MAIL_ENCRYPTION)%'
            $MAIL_DESTINATION: '%env(MAIL_DESTINATION)%'
 
    
    App\Service\BindService:
        arguments:
            # Autowiring se encarga de HttpClientInterface. 
            # Mapeamos expl√≠citamente los strings:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $BIND_CLIENT_ID: '%env(BIND_CLIENT_ID)%'
            $BIND_CLIENT_SECRET: '%env(BIND_CLIENT_SECRET)%'
            $BIND_API_URL: '%env(BIND_API_URL)%'
            $BIND_CVU_ORIGEN: '%env(BIND_CVU_ORIGEN)%'
            $BIND_TOKEN_URL: '%env(BIND_TOKEN_URL)%'
            $BIND_SCOPE: '%env(BIND_SCOPE)%' 
            $BIND_ENABLE_REAL_TRANSFER: '%env(bool:BIND_ENABLE_REAL_TRANSFER)%' 

    App\Service\BindServiceInterface: '@App\Service\BindService'


    App\Service\TransferManager:
        arguments:
            $finpaySettlementLogger: '@monolog.logger.finpay_settlement'
            $logFilePath: '%kernel.logs_dir%/transferencias_diarias.log'
            $BIND_ENABLE_REAL_TRANSFER: '%env(bool:BIND_ENABLE_REAL_TRANSFER)%'
    
    App\Service\MuteSettlementService:
        arguments:
            $bindService: '@App\Service\BindServiceInterface'
            $notifier: '@App\Service\Notifier'
            $dbConnection: '@doctrine.dbal.default_connection'
            $logger: '@monolog.logger.mute_automation'
            $logFilePath: '%kernel.logs_dir%/automatizacion_mute.log'
            $cvuOrigen: '%env(MUTE_CVU_ORIGEN)%'
            $cvuTercero: '%env(MUTE_CVU_TERCERO)%'
            $cvuPagosDigitales: '%env(MUTE_CVU_PAGOSDIGITALES)%'
            $comisionPorcentaje: '%env(float:MUTE_COMISION_PORCENTAJE)%'
            $ivaPorcentaje: '%env(float:MUTE_IVA_PORCENTAJE)%'
            $emailDestino: '%env(MUTE_EMAIL_DESTINO)%'
            $enableRealTransfer: '%env(bool:MUTE_ENABLE_REAL_TRANSFER)%'